IF(EXISTS(SELECT * FROM SYSOBJECTS WHERE XTYPE='P' AND NAME='Sp_DeleteTemplates'))
	DROP PROCEDURE Sp_DeleteTemplates
GO

CREATE PROCEDURE [dbo].Sp_DeleteTemplates
	@Id VARCHAR(200)
AS
	DELETE FROM EMR_TEMPLATE WHERE RECORDID = @Id
GO
 