CREATE PROCEDURE [dbo].[Sp_SelectPatients]
	@name VARCHAR(20)
AS
	IF @name IS NULL
		SELECT PA_ID, PA_BEINHOSPITAL_CODE, PA_NAME, PA_SEX, PA_PRITHTIME FROM EMR_PATIENTS
	ELSE
		SELECT PA_ID, PA_BEINHOSPITAL_CODE, PA_NAME, PA_SEX, PA_PRITHTIME FROM EMR_PATIENTS WHERE PA_NAME LIKE  '%' + @name + '%'

GO
 