IF(EXISTS(SELECT * FROM SYSOBJECTS WHERE XTYPE='P' AND NAME='Sp_SelectCaseHistory'))
	DROP PROCEDURE Sp_SelectCaseHistory
GO

CREATE PROCEDURE [dbo].[Sp_SelectCaseHistory]
	@patientId VARCHAR(100)
AS
		SELECT 
			RECORDID, 
			PA_ID, 
			FILENAME, 
			FILETITLE, 
			FILECONTENT, 
			FILEFORMAT, 
			DEPARTMENTID, 
			TEMPLATETYPE,
			KEYDATANAMES,
			TEMPLATEFLAGS,
			OWNERID,
			OWNERLEVEL,
			CREATEDBYID,
			CREATEDBY
		FROM EMR_CASEHISTORY
		WHERE PA_ID = @patientId
GO